sprint_5
ClevertecFrontendLab/AntonSakovsky pull request #7
Opened 2024-03-25 21:14 UTC by AntonSakovsky

2024-03-25 21:16 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-25 21:25 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 09:39 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 5.
Количество непройденных тестов: 5.

2024-03-26 09:44 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 09:49 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 10:01 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 10:32 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 11:36 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 40%.
Общее количество тестов: 5.
Количество непройденных тестов: 3.

2024-03-26 12:36 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 5.
Количество непройденных тестов: 5.

2024-03-26 13:40 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 40%.
Общее количество тестов: 5.
Количество непройденных тестов: 3.

2024-03-26 20:08 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 22:48 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-26 22:54 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 20%.
Общее количество тестов: 5.
Количество непройденных тестов: 4.

2024-03-27 16:33 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 5.
Количество непройденных тестов: 5.

2024-03-27 16:48 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 40%.
Общее количество тестов: 5.
Количество непройденных тестов: 3.

2024-03-27 17:25 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711560330/settings-sider-pro_833x900.png)

2024-03-28 07:10 UTC, vvikota requested changes

2024-03-28 07:10 UTC, vvikota commented on src/components/inputs/PasswordInput.tsx
>              { pattern: /^(?=.*[A-Z])(?=.*\d)[A-Za-z0-9]{8,}$/, message: '' },
регулярки в константы вынести

2024-03-28 07:10 UTC, vvikota commented on src/components/inputs/UploadInput/UploadInput.tsx
> +        const onResize = () => {
const onResize = () => setWindowWidth(window.innerWidth)

2024-03-28 07:10 UTC, vvikota commented on src/components/modals/BuyTariffInfoModal/BuyTariffInfoModal.module.css
> +    font-size: 24px;
размеры и жирность, цвет шрифта в константы, те что повторяются

2024-03-28 07:10 UTC, vvikota commented on src/components/modals/BuyTariffInfoModal/BuyTariffInfoModal.module.css
> +    margin-top: 24px;
отступы также в константы

2024-03-28 07:10 UTC, vvikota commented on src/components/modals/ErrorModalSmall/ErrorModalSmall.tsx
> +    closable?: boolean;
для удобства необязательные параметры вниз перемещай

2024-03-28 07:10 UTC, vvikota commented on src/components/modals/TarifDrawer/TarifDrawer.tsx
> +    const onFieldsChange = () => {
фигурные скобки не нужны

2024-03-28 07:43 UTC, kvadratikk requested changes

2024-03-28 07:43 UTC, kvadratikk commented on src/pages/feedback-page/Content/FeedbackContent.tsx
фотка не показывается. если загрузилась и не успела отобразиться, пришли скрин со своих тестов пожалуйста
![image](https://github.com/ClevertecFrontendLab/AntonSakovsky/assets/78285127/fe8672f2-6d18-40c0-93fe-f45ce4dd0055)

2024-03-28 07:43 UTC, kvadratikk commented on src/pages/profile-page/ProfilePage.tsx
почта не поменялась на новую, пароли очищаем
![image](https://github.com/ClevertecFrontendLab/AntonSakovsky/assets/78285127/27d21ff4-8b6b-453d-957f-de4243923248)

2024-03-28 07:43 UTC, kvadratikk commented on src/pages/settings-page/SettingsPage.tsx
сверься с макетом, там фон растягивается 
![image](https://github.com/ClevertecFrontendLab/AntonSakovsky/assets/78285127/5da8586a-127d-4419-9b76-a4397df0532a)

2024-03-28 07:43 UTC, kvadratikk commented on src/pages/settings-page/Content/ContentSetting/Settings.tsx
> +        : false;
const proIsActive = Boolean(availableTariffs.find((tariff) => tariff._id === userTariff?.tariffId))

2024-03-28 07:43 UTC, kvadratikk commented on src/pages/settings-page/Content/ContentSetting/Settings.tsx
> +        </div>
сделай массив элементов и по нему через мап создавай айтемы

2024-03-28 07:43 UTC, kvadratikk commented on src/pages/settings-page/Content/SettingsContent.tsx
> +                    closeHandler={() => setDrawerVisible(false)}
вынеси в хэндлер-функцию

2024-03-28 11:57 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-28 12:08 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711627708/settings-sider-pro_833x900.png)

2024-03-28 12:10 UTC, AntonSakovsky commented on src/pages/feedback-page/Content/FeedbackContent.tsx
![feedbacks with photo_1440x900](https://github.com/ClevertecFrontendLab/AntonSakovsky/assets/158065865/3380223c-0683-400e-aa23-83ad4be07b7c)

P.S.: В тестах иногда может не успевать загрузить первое фото

2024-03-28 12:54 UTC, vvikota approved these changes

2024-03-28 13:02 UTC, kvadratikk requested changes

2024-03-28 19:41 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 80%.
Общее количество тестов: 5.
Количество непройденных тестов: 1.

2024-03-28 19:44 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AntonSakovsky/1711655052/settings-sider-pro_833x900.png)

2024-03-28 19:59 UTC, merged